<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class XamppIncidentDbSeeder extends Seeder
{
    /**
     * Seed the application's database with the current XAMPP incident_db snapshot.
     */
    public function run(): void
    {
        $this->clearTables();

        DB::table('subdivisions')->insert([
            [
                'subdivision_id' => 1,
                'subdivision_name' => 'Subdivision blk1',
                'address' => '123 Main Street',
                'contact_person' => 'John Doe',
                'contact_number' => '09171234567',
                'email' => 'sample@subdivision.com',
                'status' => 'Active',
                'created_at' => '2026-03-26 13:54:09',
                'deleted_at' => null,
            ],
            [
                'subdivision_id' => 2,
                'subdivision_name' => 'Dona Maria dizon',
                'address' => 'calasiao',
                'contact_person' => 'dean',
                'contact_number' => '123456789',
                'email' => 'dona@gmail.com',
                'status' => 'Active',
                'created_at' => '2026-03-26 14:27:02',
                'deleted_at' => null,
            ],
            [
                'subdivision_id' => 3,
                'subdivision_name' => 'malabago',
                'address' => 'umc',
                'contact_person' => 'troy',
                'contact_number' => '44444',
                'email' => 'troy@gmail.com',
                'status' => 'Active',
                'created_at' => '2026-03-28 13:05:18',
                'deleted_at' => null,
            ],
            [
                'subdivision_id' => 4,
                'subdivision_name' => '3133',
                'address' => '31133',
                'contact_person' => null,
                'contact_number' => null,
                'email' => null,
                'status' => 'Active',
                'created_at' => '2026-04-01 13:11:37',
                'deleted_at' => null,
            ],
        ]);

        DB::table('residents')->insert([
            [
                'resident_id' => 1,
                'subdivision_id' => 2,
                'full_name' => 'gab',
                'phone' => '123456',
                'email' => 'gab@gmaail.com',
                'address_or_unit' => '2',
                'resident_code' => '123',
                'status' => 'Active',
                'created_at' => '2026-03-27 02:12:57',
            ],
            [
                'resident_id' => 2,
                'subdivision_id' => 2,
                'full_name' => 'kim',
                'phone' => '123456789',
                'email' => 'kim@gmail.com',
                'address_or_unit' => 'BLK4',
                'resident_code' => '87654',
                'status' => 'Active',
                'created_at' => '2026-03-28 12:34:24',
            ],
            [
                'resident_id' => 3,
                'subdivision_id' => 2,
                'full_name' => 'rj',
                'phone' => '12313',
                'email' => 'rj@gmail.com',
                'address_or_unit' => 'BLK4',
                'resident_code' => '159753',
                'status' => 'Active',
                'created_at' => '2026-03-28 13:13:56',
            ],
            [
                'resident_id' => 4,
                'subdivision_id' => 2,
                'full_name' => 'ico',
                'phone' => '13131133dada',
                'email' => 'ico@gmail.com',
                'address_or_unit' => '2',
                'resident_code' => '090909',
                'status' => 'Active',
                'created_at' => '2026-03-28 13:18:17',
            ],
            [
                'resident_id' => 5,
                'subdivision_id' => 2,
                'full_name' => 'jose',
                'phone' => '12345',
                'email' => 'jose@gmail.com',
                'address_or_unit' => '4',
                'resident_code' => '00001',
                'status' => 'Active',
                'created_at' => '2026-03-30 11:41:40',
            ],
        ]);

        DB::table('users')->insert([
            [
                'user_id' => 1,
                'full_name' => 'System Test Administrator',
                'email' => 'admin@example.com',
                'password' => '$2y$12$ebbG3eS8fHhnCpLfPK2DxOPzGSz5e0/RsetejZkLuIaHNHSYLHeoO',
                'role' => 'admin',
                'subdivision_id' => null,
                'visitor_notifications_read_at' => '2026-04-02 08:50:20',
                'visitor_notifications_cleared_at' => '2026-04-02 08:50:20',
                'visitor_notification_read_keys' => '[]',
                'created_at' => '2026-03-26 13:54:09',
                'surname' => 'Administrator',
                'first_name' => 'System',
                'middle_name' => 'Test',
                'extension' => null,
                'deleted_at' => null,
            ],
            [
                'user_id' => 3,
                'full_name' => 'ralph',
                'email' => 'ralph@gmail.com',
                'password' => '$2y$12$oCiHFFZFkRneh9mPr9VJW.6jquHfWC88jd8jsni2gNLlvOQDaK9BG',
                'role' => 'security',
                'subdivision_id' => 2,
                'visitor_notifications_read_at' => null,
                'visitor_notifications_cleared_at' => null,
                'visitor_notification_read_keys' => null,
                'created_at' => '2026-03-26 14:31:08',
                'surname' => null,
                'first_name' => 'ralph',
                'middle_name' => null,
                'extension' => null,
                'deleted_at' => null,
            ],
            [
                'user_id' => 4,
                'full_name' => 'dean',
                'email' => 'dean@example.com',
                'password' => '$2y$12$4PNjKDRqBWqNCXHxVIWZAOlOVOG1SifDI15uRZY22Z0pmP4XfUUue',
                'role' => 'investigator',
                'subdivision_id' => 2,
                'visitor_notifications_read_at' => null,
                'visitor_notifications_cleared_at' => null,
                'visitor_notification_read_keys' => null,
                'created_at' => '2026-03-26 14:34:40',
                'surname' => null,
                'first_name' => 'dean',
                'middle_name' => null,
                'extension' => null,
                'deleted_at' => null,
            ],
            [
                'user_id' => 5,
                'full_name' => 'kim',
                'email' => 'kim@gmail.com',
                'password' => '$2y$10$9jd.giZxqHGtQ5dhZHCK.uYgE8tWQhsYmtefkisydk4zfRqU/072u',
                'role' => 'staff',
                'subdivision_id' => 2,
                'visitor_notifications_read_at' => null,
                'visitor_notifications_cleared_at' => null,
                'visitor_notification_read_keys' => null,
                'created_at' => '2026-03-27 06:28:57',
                'surname' => null,
                'first_name' => 'kim',
                'middle_name' => null,
                'extension' => null,
                'deleted_at' => null,
            ],
            [
                'user_id' => 7,
                'full_name' => 'rj',
                'email' => 'rj@gmail.com',
                'password' => '$2y$10$hvDJRrjlQPfu.Tamg5R2x.0hULDf.3b1h/DRWWbYsfDtZILyzaikS',
                'role' => 'staff',
                'subdivision_id' => 2,
                'visitor_notifications_read_at' => null,
                'visitor_notifications_cleared_at' => null,
                'visitor_notification_read_keys' => null,
                'created_at' => '2026-03-28 13:12:43',
                'surname' => null,
                'first_name' => 'rj',
                'middle_name' => null,
                'extension' => null,
                'deleted_at' => null,
            ],
            [
                'user_id' => 8,
                'full_name' => 'ico',
                'email' => 'ico@gmail.com',
                'password' => '$2y$12$c8ZwzB3KGZjMY9LXtLD0AeRv.Ysb0n4c4fBG0geBQi25VGPLzr36.',
                'role' => 'staff',
                'subdivision_id' => 2,
                'visitor_notifications_read_at' => null,
                'visitor_notifications_cleared_at' => null,
                'visitor_notification_read_keys' => null,
                'created_at' => '2026-03-28 13:17:19',
                'surname' => null,
                'first_name' => 'ico',
                'middle_name' => null,
                'extension' => null,
                'deleted_at' => null,
            ],
        ]);

        DB::table('visitors')->insert([
            [
                'visitor_id' => 1,
                'subdivision_id' => 2,
                'full_name' => 'bong',
                'phone' => '123456789',
                'id_number' => '123',
                'company' => 'bsit',
                'purpose' => 'meeting',
                'host_employee' => null,
                'check_in' => '2026-03-26 22:56:04',
                'check_out' => '2026-03-26 22:56:07',
                'status' => 'Checked Out',
                'surname' => null,
                'first_name' => 'bong',
                'middle_initials' => null,
                'extension' => null,
                'deleted_at' => null,
            ],
            [
                'visitor_id' => 2,
                'subdivision_id' => 2,
                'full_name' => 'johhny',
                'phone' => '123456789',
                'id_number' => '123456',
                'company' => 'bsit',
                'purpose' => 'meeting',
                'host_employee' => 'visitor',
                'check_in' => '2026-03-27 10:08:28',
                'check_out' => '2026-03-27 10:11:17',
                'status' => 'Checked Out',
                'surname' => null,
                'first_name' => 'johhny',
                'middle_initials' => null,
                'extension' => null,
                'deleted_at' => null,
            ],
            [
                'visitor_id' => 3,
                'subdivision_id' => 2,
                'full_name' => 'kim',
                'phone' => '456',
                'id_number' => '00038555',
                'company' => 'bsit',
                'purpose' => 'meeting',
                'host_employee' => 'visitor',
                'check_in' => '2026-03-28 20:36:26',
                'check_out' => '2026-03-28 21:24:06',
                'status' => 'Checked Out',
                'surname' => null,
                'first_name' => 'kim',
                'middle_initials' => null,
                'extension' => null,
                'deleted_at' => null,
            ],
            [
                'visitor_id' => 4,
                'subdivision_id' => 2,
                'full_name' => 'dean',
                'phone' => '789999',
                'id_number' => '5454',
                'company' => 'bsit',
                'purpose' => 'visitor',
                'host_employee' => 'visitor',
                'check_in' => '2026-03-28 20:43:35',
                'check_out' => '2026-04-02 15:39:07',
                'status' => 'Checked Out',
                'surname' => null,
                'first_name' => 'dean',
                'middle_initials' => null,
                'extension' => null,
                'deleted_at' => null,
            ],
            [
                'visitor_id' => 6,
                'subdivision_id' => 4,
                'full_name' => 'test m test',
                'phone' => '098273128903',
                'id_number' => '1',
                'company' => 'outsoar',
                'purpose' => 'aasdasdas',
                'host_employee' => 'test',
                'check_in' => '2026-04-02 17:29:47',
                'check_out' => null,
                'status' => 'Inside',
                'surname' => 'test',
                'first_name' => 'test',
                'middle_initials' => 'm',
                'extension' => null,
                'deleted_at' => null,
            ],
        ]);

        DB::table('incidents')->insert([
            [
                'incident_id' => 1,
                'subdivision_id' => 2,
                'title' => '11',
                'description' => '1',
                'category' => '1',
                'location' => '1',
                'incident_date' => '2026-03-26 15:32:00',
                'status' => 'Resolved',
                'proof_photo_path' => null,
                'reported_by' => 3,
                'assigned_to' => null,
                'created_at' => '2026-03-26 14:33:35',
                'verified_resident_id' => null,
                'verification_method' => null,
                'verified_at' => null,
            ],
            [
                'incident_id' => 2,
                'subdivision_id' => 2,
                'title' => 'eawea',
                'description' => 'aewaew',
                'category' => 'aeaww',
                'location' => 'aea',
                'incident_date' => '2026-03-28 13:29:00',
                'status' => 'Under Investigation',
                'proof_photo_path' => null,
                'reported_by' => 4,
                'assigned_to' => null,
                'created_at' => '2026-03-28 12:30:06',
                'verified_resident_id' => null,
                'verification_method' => null,
                'verified_at' => null,
            ],
            [
                'incident_id' => 3,
                'subdivision_id' => 2,
                'title' => 'wq',
                'description' => 'qQW',
                'category' => '1',
                'location' => 'EAW',
                'incident_date' => '2026-03-28 13:31:00',
                'status' => 'Open',
                'proof_photo_path' => null,
                'reported_by' => 5,
                'assigned_to' => null,
                'created_at' => '2026-03-28 12:32:51',
                'verified_resident_id' => 1,
                'verification_method' => 'manual_code',
                'verified_at' => '2026-03-28 13:32:51',
            ],
            [
                'incident_id' => 4,
                'subdivision_id' => 2,
                'title' => 'EAW',
                'description' => 'FEAW',
                'category' => 'FEWA',
                'location' => 'AEWFE',
                'incident_date' => '2026-03-28 13:34:00',
                'status' => 'Open',
                'proof_photo_path' => null,
                'reported_by' => 5,
                'assigned_to' => null,
                'created_at' => '2026-03-28 12:34:54',
                'verified_resident_id' => null,
                'verification_method' => null,
                'verified_at' => null,
            ],
            [
                'incident_id' => 6,
                'subdivision_id' => 2,
                'title' => 'walang  ilaw',
                'description' => 'www',
                'category' => 'ww',
                'location' => 'blk1',
                'incident_date' => '2026-03-28 14:14:00',
                'status' => 'Open',
                'proof_photo_path' => null,
                'reported_by' => 7,
                'assigned_to' => null,
                'created_at' => '2026-03-28 13:14:54',
                'verified_resident_id' => null,
                'verification_method' => null,
                'verified_at' => null,
            ],
            [
                'incident_id' => 7,
                'subdivision_id' => 2,
                'title' => 'nanakawan',
                'description' => 'nanaakawan ng  gabi',
                'category' => '1',
                'location' => 'sub 1 blk 2',
                'incident_date' => '2026-03-28 14:15:00',
                'status' => 'Open',
                'proof_photo_path' => null,
                'reported_by' => 7,
                'assigned_to' => null,
                'created_at' => '2026-03-28 13:15:58',
                'verified_resident_id' => 3,
                'verification_method' => 'manual_code',
                'verified_at' => '2026-03-28 14:15:58',
            ],
            [
                'incident_id' => 8,
                'subdivision_id' => 2,
                'title' => 'walang tubig',
                'description' => 'need ayusin may pupuntahan ako',
                'category' => 'nasira yung tubigan need maayyos',
                'location' => 'calasiao',
                'incident_date' => '2026-03-28 14:18:00',
                'status' => 'Resolved',
                'proof_photo_path' => null,
                'reported_by' => 8,
                'assigned_to' => null,
                'created_at' => '2026-03-28 13:20:16',
                'verified_resident_id' => null,
                'verification_method' => null,
                'verified_at' => null,
            ],
            [
                'incident_id' => 9,
                'subdivision_id' => 2,
                'title' => 'need ayusin',
                'description' => 'wa',
                'category' => 'nasira',
                'location' => 'ww',
                'incident_date' => '2026-04-01 08:57:00',
                'status' => 'Open',
                'proof_photo_path' => null,
                'reported_by' => 1,
                'assigned_to' => null,
                'created_at' => '2026-04-01 07:03:26',
                'verified_resident_id' => null,
                'verification_method' => null,
                'verified_at' => null,
            ],
        ]);
    }

    /**
     * Clear tables in child-to-parent order to satisfy foreign keys.
     */
    private function clearTables(): void
    {
        foreach ([
            'incident_photos',
            'incidents',
            'visitors',
            'gate_visitor_logs',
            'users',
            'residents',
            'subdivisions',
        ] as $table) {
            DB::table($table)->delete();
        }
    }
}
